//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testir.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pen
    {
        public int id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> viewid { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Type Type { get; set; }
        public virtual View View { get; set; }
    }
}
